### ISSUE TITLE
I got an error while import your gradle project on eclipse 

### ISSUE THREAD

**Issue by YokeshGithub** [axitchandora/GeekTrust-Challenge-DoReMi-Subscription#1]
![Screenshot (489)](https://github.com/axitchandora/GeekTrust-Challenge-DoReMi-Subscription/assets/111746788/e8bbb701-a7c2-407b-980b-bb2f03450d61)

**Comment by axitchandora** [comment]
Could you try to open it in Java Intellij?

**Comment by YokeshGithub** [comment]
> Could you try to open it in Java Intellij?

Okay let me try..

**Comment by YokeshGithub** [comment]
![Screenshot (490)](https://github.com/axitchandora/GeekTrust-Challenge-DoReMi-Subscription/assets/111746788/74e9d138-2034-4628-ba13-0321f4d3fa61)



And it will show like this on Intellij after open the project on Intellij

**Comment by axitchandora** [comment]
There is some issue with your JDK. Refer to this https://stackoverflow.com/questions/30328994/invalid-gradle-jdk-configuration-found.
